[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bank = "9ojBDTe6p69cwfk5b2x8McD8TtFieAgTQdvWzDYpXs2z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keypairs/jitgabCEJMy37dfkGpY1fRPCiovsvNiUivKTiqwpazn.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
